<?php

namespace Tests;

use Illuminate\Foundation\Testing\RefreshDatabase;

abstract class TenantTestCase extends TestCase
{
    use RefreshDatabase;

    protected function refreshApplication(): void
    {
        parent::refreshApplication(); // TODO: Change the autogenerated stub
        $this->artisan('migrate');
    }
    protected function assertSystemDatabaseHas($table, array $data, $connection = null): void
    {
        $this->assertDatabaseHas($table, $data, env('DB_CONNECTION'));
    }
    protected function assertSystemDatabaseMissing($table, array $data): void
    {
        $this->assertDatabaseMissing($table, $data, env('DB_CONNECTION'));
    }
}
